name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # 👈 プロジェクトに合わせて変更してください
          cache: 'yarn'

      # sharpのためにlibvipsをインストールするステップ 👇
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # このステップを追加 👇
      - name: Rebuild sharp
        run: npm rebuild sharp
      - name: Build with Astro
        run: yarn run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Astroのビルド出力ディレクトリ (通常は 'dist')
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
